Added a nav-bar to the header section
sulenchy/Mentee-git-show pull request #2
Opened 2024-10-30 11:44 UTC by SilvernusIfoghale

Updated the header section of the index.html file

2024-10-30 11:52 UTC, sulenchy commented on src/index.html
> +    <header style="padding: 0px 20px">
This line looks good to me

2024-10-30 11:53 UTC, sulenchy requested changes
Please, fix the merge conflict on the PR

2024-10-30 12:13 UTC, sulenchy commented on src/index.html
> +            <a href="#">Home</a>
```suggestion
            <a href="#home">Home</a>
```

2024-10-30 12:28 UTC, SilvernusIfoghale commented
Fixed

2024-11-02 11:18 UTC, sulenchy commented on src/index.html
> +            <a href="#">Services</a>
```suggestion
            <a href="#services">Services</a>
```

2024-11-02 11:18 UTC, sulenchy approved these changes
Thanks for the changes

2024-11-02 11:18 UTC, merged